# Generated by Django 4.0.5 on 2022-06-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_manager_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='username',
        ),
    ]
