# Generated by Django 4.0.5 on 2022-07-22 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_manager_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('worksWithAgents', models.BooleanField(default=False)),
                ('receiveRecommendations', models.BooleanField(default=True)),
                ('isCollaborator', models.BooleanField(default=False)),
                ('isOwner', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IBAN',
            fields=[
                ('code', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='worksWithAgents',
            field=models.BooleanField(default=False),
        ),
    ]
