# Generated by Django 4.0.5 on 2022-07-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_alter_property_owner'),
        ('Account', '0005_administrator_enterprise_iban_remove_manager_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manager',
        ),
        migrations.AddField(
            model_name='iban',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.enterprise'),
        ),
        migrations.AddField(
            model_name='iban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.administrator'),
        ),
    ]
