# Generated by Django 4.0.5 on 2022-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='paymentTotal',
            field=models.FloatField(default=0),
        ),
    ]
