# Generated by Django 4.0.5 on 2022-09-06 12:48

import apps.models.modelsProperty
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_property_paymenttotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='paymentTotal',
        ),
        migrations.AddField(
            model_name='property',
            name='currency_type',
            field=models.CharField(choices=[('EURO', 'EURO'), ('RON', 'RON')], default='RON', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='usable_area',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1984), apps.models.modelsProperty.max_value_current_year]),
            preserve_default=False,
        ),
    ]
