# Generated by Django 4.0.5 on 2022-09-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_property_paymenttotal'),
        ('Fee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='balance',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='fee',
            name='associatedProperty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Property.property'),
        ),
    ]
