# Generated by Django 4.0.5 on 2022-09-01 16:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='isCollaborator',
            field=models.BooleanField(default=False, verbose_name='Collaborates with other administrators'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='isOwner',
            field=models.BooleanField(default=False, verbose_name='Has properties'),
        ),
    ]
