# Generated by Django 4.0.5 on 2022-09-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_managers_remove_user_isadministrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='isAdministrator',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='isRealEstateAgent',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='isTenant',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='isAdministrator',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='isRealEstateAgent',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='isTenant',
        ),
        migrations.AddField(
            model_name='user',
            name='isAdministrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isRealEstateAgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isTenant',
            field=models.BooleanField(default=False),
        ),
    ]
