# Generated by Django 4.0.5 on 2022-09-06 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_administrator_isadministrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='userConnection',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='userConnection',
        ),
        migrations.AddField(
            model_name='user',
            name='userConnection',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
