# Generated by Django 4.0.4 on 2022-06-12 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Bill added')),
                ('bill_deadline', models.DateField(blank=True, default=None, null=True, verbose_name='due date')),
                ('value', models.FloatField()),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('payee_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payee', to=settings.AUTH_USER_MODEL)),
                ('propriety_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propriety_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility_bills.utilitytype', verbose_name='utility type')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(verbose_name='Payment date')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_bills.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility_bills.provider'),
        ),
    ]
