# Generated by Django 4.0.5 on 2022-06-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Fee.utilitytype'),
        ),
        migrations.AddField(
            model_name='provider',
            name='type2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='utility_type_2', to='Fee.utilitytype', verbose_name='utility type 2 (optional)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='type3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='utility_type_3', to='Fee.utilitytype', verbose_name='utility type 3 (optional)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Fee.provider'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='value',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='utility_type', to='Fee.utilitytype', verbose_name='utility type'),
        ),
    ]
