# Generated by Django 4.0.5 on 2022-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fee', '0002_bill_type_provider_type2_provider_type3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='type3',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='type',
        ),
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.ManyToManyField(to='Fee.utilitytype'),
        ),
    ]
