# Generated by Django 4.0.5 on 2022-06-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='region',
        ),
    ]
